package com.darkorbit

enum class setBonusId {
	/* 0 */ none,
	/* 1 */ SET_BONUS_ABILITY_FERVOR,
	/* 2 */ SET_BONUS_ATTRIBUTE_LF5_LDN,
	/* 3 */ SET_BONUS_SLOW_TARGET,
	/* 4 */ SET_BONUS_STRIKE_RATE,
	/* 5 */ SET_BONUS_ATTRIBUTE_LF5_LD,
	/* 6 */ SET_BONUS_ATTRIBUTE_DRIVE_RANGE,
	/* 7 */ SET_BONUS_ATTRIBUTE_DRIVE_DAMAGE,
	/* 8 */ SET_BONUS_ATTRIBUTE_DRIVE_EFFECT_TIME,
	/* 9 */ SET_BONUS_ATTRIBUTE_DRIVE_VISUAL,
	/* 10 */ SET_BONUS_ATTRIBUTE_DRIVE_LEFT_DAMAGE,
}
