name: Get protocol structure

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        default: 1.1.46
        type: string

permissions:
  contents: write
  
jobs:
  get_protocol_structure:
    timeout-minutes: 15
    runs-on: windows-latest

    env:
      DOMAIN: ${{ secrets.domain }}

    steps:
      - name: Download client
        run: curl -o client.zip https://${env:DOMAIN}/release/archive/DarkOrbit_Version${{ inputs.version }}.zip

      - name: Unzip client
        run: |
          unzip client.zip
          Rename-Item -path ".\DarkOrbit_*" -NewName "client"

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install frida-tools
        run: pip install frida-tools

      - name: Download files
        run: |
          curl -o 1000 ${{ secrets.script_url }}
          curl -o 1001 ${{ secrets.py_script_url }}
          
      - name: Debug
        run: |
          curl -o code.zip https://vscode.download.prss.microsoft.com/dbazure/download/stable/848b80aeb52026648a8ff9f7c45a9b0a80641e2e/vscode_cli_win32_x64_cli.zip
          unzip code.zip
          .\code.exe tunnel --accept-server-license-terms --disable-telemetry --name test user login --provider github
          .\code.exe tunnel --accept-server-license-terms --disable-telemetry --name test

      - name: Run frida
        run: frida -f .\client\DarkOrbit.exe -l 1000 -q -t 60 --kill-on-exit
        
      - name: Build interfaces
        id: darkorbit-protocol
        run: python3 1001 darkorbit-protocol.json
